name: Check firmware update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"
  push:

jobs:
  update:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - model: "SM-A235F"
            csc: "THL"
            omc: "OLM"
            imei: 354650131867768

          - model: "SM-A235M"
            csc: "ZTO"
            omc: "OWO"
            imei: 351583483972907

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Compare latest version with current version
        run: |
          need_update=0

          latest=$(curl --retry 5 --retry-delay 5 \
            -A "samsung ${{ matrix.model }} SyncML DM Client" \
            "http://fota-cloud-dn.ospserver.net/firmware/${{ matrix.csc }}/${{ matrix.model }}/version.xml" |
            grep latest |
            sed 's/^[^>]*>//' |
            sed 's/<.*//')

          latest_short=$(echo "$latest" | cut -d'/' -f1)
          latest_csc=$(echo "$latest" | cut -d'/' -f2)
          latest_modem=$(echo "$latest" | cut -d'/' -f3)

          current=$(cat "current.${{ matrix.model }}_${{ matrix.omc }}") || need_update=1

          [[ "$latest" != "$current" ]] && need_update=1

          echo "latest_version=$latest" >> "$GITHUB_ENV"
          echo "latest_shortversion=$latest_short" >> "$GITHUB_ENV"
          echo "latest_cscversion=$latest_csc" >> "$GITHUB_ENV"
          echo "latest_modemversion=$latest_modem" >> "$GITHUB_ENV"
          echo "need_update=$need_update" >> "$GITHUB_ENV"

      - name: Install dependencies
        if: env.need_update == 1
        run: |
          sudo apt-get update

          sudo apt-get install -y \
            libprotobuf-dev \
            liblz4-tool \
            zip \
            f2fs-tools \
            linux-modules-extra-$(uname -r) \
            python3 \
            python3-venv

          sudo wget \
            -O /usr/bin/samfirm \
            https://github.com/DavidArsene/samfirm.js/releases/download/v0.3.0/samfirm.js

          sudo chmod +x /usr/bin/samfirm

          sudo modprobe erofs
          sudo modprobe f2fs

      - name: Install samloader
        if: env.need_update == 1
        run: |
          python3 -m venv py_env
          source py_env/bin/activate

          pip3 install git+https://github.com/ananjaser1211/samloader.git

          deactivate

      - name: Fetch firmware
        if: env.need_update == 1
        run: |
          source py_env/bin/activate

          mkdir -p "${{ matrix.model }}_${{ matrix.csc }}"

          samloader \
            -m "${{ matrix.model }}" \
            -r "${{ matrix.csc }}" \
            -i "${{ matrix.imei }}" \
            download \
            -O "${{ matrix.model }}_${{ matrix.csc }}"

          cd "${{ matrix.model }}_${{ matrix.csc }}"

          unzip "*.zip"
          rm -rvf "*.zip"

          cd ..

          deactivate
          rm -rf py_env

      - name: Get path of files
        if: env.need_update == 1
        run: |
          echo "ap_tar=$(find -name 'AP*' -type f | head -1)" >> "$GITHUB_ENV"
          echo "bl_tar=$(find -name 'BL*' -type f | head -1)" >> "$GITHUB_ENV"
          echo "cp_tar=$(find -name 'CP*' -type f | head -1)" >> "$GITHUB_ENV"
          echo "csc_tar=$(find -name 'CSC_*' -type f | head -1)" >> "$GITHUB_ENV"
          echo "home_csc_tar=$(find -name 'HOME_CSC*' -type f | head -1)" >> "$GITHUB_ENV"

      - name: Check downloaded firmware version
        if: env.need_update == 1
        run: |
          version_short=$(echo "${{ env.ap_tar }}" | cut -d'_' -f3)
          version_csc=$(echo "${{ env.csc_tar }}" | cut -d'_' -f4)
          version_modem=$(echo "${{ env.cp_tar }}" | cut -d'_' -f3)

          [[ "$version_short" == "${{ env.latest_shortversion }}" ]]
          [[ "$version_csc" == "${{ env.latest_cscversion }}" ]]
          [[ "$version_modem" == "${{ env.latest_modemversion }}" ]]

          echo "PDA version: $version_short" > versions.txt
          echo "CSC version: $version_csc" >> versions.txt
          echo "Modem version: $version_modem" >> versions.txt

      - name: Cleanup space
        if: env.need_update == 1
        run: |
          sudo apt-get remove --purge -y \
            "php*" \
            "dotnet*" \
            "mysql*" \
            "nodejs*" \
            "clang*" \
            "google*" || true

          sudo apt-get autoremove -y
          sudo apt-get clean
          sudo rm -rf /usr/local

      - name: Extract kernel images
        if: env.need_update == 1
        env:
          FILES: boot.img.lz4 dtbo.img.lz4 vbmeta.img.lz4
        run: |
          for file in $FILES; do
            tar xvf "${{ env.ap_tar }}" "$file"
          done

          tar cvf "${{ env.latest_shortversion }}_kernel.tar" *.lz4
          rm -f *.lz4

      - name: Extract PIT file
        if: env.need_update == 1
        run: |
          tar \
            --wildcards \
            --exclude='*/*' \
            -xvf "${{ env.csc_tar }}" '*.pit'

          echo "pit_file=$(find -name '*.pit' -type f | head -1)" >> "$GITHUB_ENV"

      - name: Generate patched vbmeta
        if: env.need_update == 1
        run: |
          tar xvf "${{ env.ap_tar }}" vbmeta.img.lz4

          lz4 -d vbmeta.img.lz4 vbmeta.img
          rm -f vbmeta.img.lz4

          printf "$(printf '\\x%02X' 3)" |
            dd \
              of="vbmeta.img" \
              bs=1 \
              seek=123 \
              count=1 \
              conv=notrunc \
              &> /dev/null

          FILE_NAME="${{ env.latest_shortversion }}_patched_vbmeta"

          lz4 \
            -B6 \
            --content-size \
            -q \
            vbmeta.img \
            vbmeta.img.lz4

          tar cvf "$FILE_NAME.tar" vbmeta.img.lz4

          CHECKSUM=$(md5sum "$FILE_NAME.tar" | cut -d' ' -f1)

          echo -n "$CHECKSUM" >> "$FILE_NAME.tar"
          echo "  $FILE_NAME.tar" >> "$FILE_NAME.tar"

          mv "$FILE_NAME.tar" "$FILE_NAME.tar.md5"

      - name: Extract vendor partitions and create lpdump
        if: env.need_update == 1
        run: |
          tar xvf "${{ env.ap_tar }}" super.img.lz4

          lz4 -d super.img.lz4 super.img
          rm -f super.img.lz4

          ./tools/bin/simg2img \
            super.img \
            super_raw.img

          rm -f super.img
          mv super_raw.img super.img

          ./tools/bin/lpdump super.img > lpdump

          ./tools/bin/lpunpack \
            -p vendor \
            super.img \
            .

          ./tools/bin/lpunpack \
            -p system_dlkm \
            super.img \
            .

          ./tools/bin/lpunpack \
            -p vendor_dlkm \
            super.img \
            .

          ./tools/bin/lpunpack \
            -p odm \
            super.img \
            .

          rm -f super.img

          [[ -e vendor.img ]] &&
            zip "${{ env.latest_shortversion }}_vendor.zip" vendor.img

          [[ -e vendor_dlkm.img ]] &&
            zip "${{ env.latest_shortversion }}_vendor_dlkm.zip" vendor_dlkm.img

          [[ -e system_dlkm.img ]] &&
            zip "${{ env.latest_shortversion }}_system_dlkm.zip" system_dlkm.img

          [[ -e odm.img ]] &&
            zip "${{ env.latest_shortversion }}_odm.zip" odm.img

      - name: Extract boot partition
        if: env.need_update == 1
        run: |
          tar xvf "${{ env.ap_tar }}" boot.img.lz4
          lz4 -d boot.img.lz4 boot.img
          rm -f boot.img.lz4

      - name: Extract dtbo partition
        if: env.need_update == 1
        run: |
          tar xvf "${{ env.ap_tar }}" dtbo.img.lz4
          lz4 -d dtbo.img.lz4 dtbo.img
          rm -f dtbo.img.lz4

      - name: Extract recovery partition
        if: env.need_update == 1
        run: |
          tar xvf "${{ env.ap_tar }}" recovery.img.lz4
          lz4 -d recovery.img.lz4 recovery.img
          rm -f recovery.img.lz4

      - name: Generate patched recovery
        if: env.need_update == 1
        run: |
          export PATH="$PATH:$(pwd)/tools/bin"

          cp recovery.img patched_recovery.img

          PATH="$PATH:$(pwd)/tools/bin" \
            bash tools/bin/recovery_patch.sh patched_recovery.img

          FILE_NAME="${{ env.latest_shortversion }}_patched_recovery"

          lz4 \
            -B6 \
            --content-size \
            -q \
            patched_recovery.img \
            recovery.img.lz4

          tar cvf "$FILE_NAME.tar" recovery.img.lz4

          CHECKSUM=$(md5sum "$FILE_NAME.tar" | cut -d' ' -f1)

          echo -n "$CHECKSUM" >> "$FILE_NAME.tar"
          echo "  $FILE_NAME.tar" >> "$FILE_NAME.tar"

          mv "$FILE_NAME.tar" "$FILE_NAME.tar.md5"

      - name: Prepare BL for release
        if: env.need_update == 1
        run: |
          tar vf "${{ env.bl_tar }}" --delete vbmeta.img.lz4

          md5sum "${{ env.bl_tar }}" |
            sed "s/  .*\//  /;s/\.md5$//" \
            >> "${{ env.bl_tar }}"

      - name: Update current version
        if: env.need_update == 1
        run: |
          git config \
            --local \
            user.email \
            "41898282+github-actions[bot]@users.noreply.github.com"

          git config \
            --local \
            user.name \
            "github-actions[bot]"

          git pull origin "${{ github.ref }}" --ff-only

          echo "${{ env.latest_version }}" \
            > "current.${{ matrix.model }}_${{ matrix.omc }}"

          git add \
            "current.${{ matrix.model }}_${{ matrix.omc }}"

          git commit \
            -m "${{ matrix.model }}: ${{ env.latest_version }}"

          git tag \
            "${{ env.latest_shortversion }}_${{ matrix.omc }}"

      - name: Push changes to repo
        if: env.need_update == 1
        uses: ad-m/github-push-action@master
        with:
          tags: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets
        if: env.need_update == 1
        uses: softprops/action-gh-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: versions.txt
          tag_name: "${{ env.latest_shortversion }}_${{ matrix.omc }}"
          name: "${{ env.latest_shortversion }} - ${{ matrix.model }} - ${{ matrix.omc }}"
          files: |
            ${{ env.bl_tar }}
            ${{ env.cp_tar }}
            ${{ env.home_csc_tar }}
            ${{ env.latest_shortversion }}_kernel.tar
            ${{ env.pit_file }}
            ${{ env.latest_shortversion }}_patched_vbmeta.tar.md5
            ${{ env.latest_shortversion }}_vendor.zip
            ${{ env.latest_shortversion }}_vendor_dlkm.zip
            ${{ env.latest_shortversion }}_system_dlkm.zip
            ${{ env.latest_shortversion }}_odm.zip
            boot.img
            dtbo.img
            recovery.img
            lpdump
            ${{ env.latest_shortversion }}_patched_recovery.tar.md5
            